name: Node.js CI
on: [push]
jobs:
  followup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: ls -al
      - run: npm install
      - run: node src\followup.mjs
      # - run: npm ci
      # - run: npm run build --if-present
      # - run: npm test

# name: hello-world
# on: push
# jobs:
#   followup:
#     runs-on: node-latest
#     steps:
#       - uses: actions/checkout@v3
#       - run: ls -al
#       - run: npm install
#       - run: node src\followup.mjs
