name: followup check
# on: [push]
on:
  push:
    branches: [main]
#  schedule:
#    # - cron: "*/5 * * * *" #test
#    - cron: "10 */1 * * *"
jobs:
  followup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: ls -al
      - run: npm install
      - run: node src/followup.mjs ${{ secrets.PORT_PIN }}
      - run: |
            starttime=`date '+%Y-%m-%dT%H:%M:%S' -d '-5 hour'`
            endtime=`date '+%Y-%m-%dT%H:%M:%S' -d '-1 hour'`
            echo "${starttime}"
            echo "${endtime}"            
            gh api repos/nipfjallet5/tvatt/actions/runs --paginate | \
            jq --arg v1 "${starttime}Z" --arg v2 "${endtime}Z" '.workflow_runs[] | select(.run_started_at > $v1) | select(.run_started_at < $v2) | select(.display_title == "followup check")' | \
            jq '.id' | \
            xargs -I {} gh api -X DELETE repos/nipfjallet5/tvatt/actions/runs/{}
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      