name: Manual Trigger Workflow

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: test gh
        run: | 
            gh --version

  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: test gh
        run: gh workflow list 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
