name: Manual Trigger Workflow

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: test gh
        run: | 
            gh --version

  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: test gh
        run: |
            gh workflow list
            today=`date '+%Y-%m-%d'`
            echo "${today}"
            gh api repos/nipfjallet5/tvatt/actions/runs --paginate | \
            jq --arg v1 "${today}T00:00:00Z" --arg v2 "${today}T23:59:59Z" '.workflow_runs[] | select(.run_started_at > $v1) | select(.run_started_at < $v2)' | \
            jq '.id'
env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# # today=`date '+%Y-%m-%d'` -d '-1 day'
# today=`date '+%Y-%m-%d'`
# echo "${today}"

# gh api repos/nipfjallet5/tvatt/actions/runs --paginate | \
# jq --arg v1 "${today}T00:00:00Z" --arg v2 "${today}T23:59:59Z" '.workflow_runs[] | select(.run_started_at > $v1) | select(.run_started_at < $v2)' | \
# jq '.id'
